angular.module("filter",[])
.controller("testfilter",function($scope){
    $scope.names=[
        'Babu',
        'Neer',
        'Mani',
        'Selva',
        'Karthi',
        'Navin'
    ];
});